### ISSUE TITLE
空格的用法：輸出到螢幕還是入候選字?

### ISSUE THREAD

**Issue by whyjz** [whyjz/rime-moetaigi#6]
目前萌台語的空格是用來把所有的選擇上輸出到螢幕。

根據 sn00151200@PTT 的建議，可考慮輸出到候選字行的替代方案 (像是新注音輸入時畫底線的部分)，讓選字更有彈性。

**Comment by AlanJui** [comment]
感覺上，可用數字鍵，自候選字行挑欲輸出的漢字，在操作上會比較便捷。

如圖所示：欲輸入「**之**」字，個人期待的操作步驟為：
![2022-03-21_10-37-15](https://user-images.githubusercontent.com/2138279/159199293-fe039cd0-a761-4ebe-bbc4-e6c206b4f6fa.png)

1. 輸入聲母：**丩** ；

2. 聲入韻母：**一** ；

3. 按 **〔PageDown〕** 鍵，要求**候選字行**往下換頁數次，直到能看到「之」字；

4. 按 **〔9〕** 鍵，選擇「之」字輸出。（可以接受在按數字鍵時，須一併按下〔Shift〕鍵）

**Comment by whyjz** [comment]
@AlanJui 感謝您的意見！抱歉我過去幾個月在偷懶，但在最新的 commit [b4a148d](https://github.com/whyjz/rime-moetaigi/commit/b4a148d100dd4b8bb317722bb26632faa178347d) 中已經實作出這裡的大部分想法了。具體來說

- 現在有了候選字行
- 待選字列表出現時，可使用空白鍵將選中的字放入候選字行
- 當候選字行有字但選字列表沒有出現時，按 "下方向鍵" 可以重新叫出選字列表
- 使用 ctrl+數字鍵就可以直接選擇在選字列表中出現的某字。

直接按下數字鍵或是按下〔Shift〕鍵後按下數字鍵挑選漢字都會因為與注音鍵位衝突 (例如ㄅ (1) 和 ㆠ (Shift+1) ) 的關係，設計上有點困難，因此這邊先用 **〔Ctrl〕搭配數字鍵** 來測試。打起來就像是下面這樣 (注意我按了 ctrl+4 打出「啉」)：

![moetaigi_issue6](https://user-images.githubusercontent.com/19339926/177230954-7a6b5506-b2ce-4e76-831f-41ed96c0ee80.gif)

不知您有什麼想法？歡迎隨時下載最新的設定檔試用看看！
